#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
from os import path

def load_tools(ctx):
    ctx.load('compiler_cxx')

def options(ctx):
    load_tools(ctx)

def configure(ctx):
    load_tools(ctx)


def build(bld):
    bld.program(
        target='test',
        source=["test.cpp"],
        use     = [])
